export const langs = [
  "English (UK)",
  "Türkçe",
  "Kurdî (Kurmancî)",
  "العربية",
  "Zaza",
  "Deutsch",
  "Русский",
  "Français (France)",
  "فارسی",
  "Español",
  "Português (Brasil)",
];
export const links = [
  "Sign Up",
  "Log in",
  "Messenger",
  "Facebook Lite",
  "Video",
  "Places",
  "Games",
  "Marketplace",
  "Meta Pay",
  "Meta Store",
  "Meta Quest",
  "Instagram",
  "Threads",
  "Fundraisers",
  "Services",
  "Voting Information Centre",
  "Privacy Policy",
  "Privacy Centre",
  "Groups",
  "About",
  "Createad",
  "Create Page",
  "Developers",
  "Careers",
  "Cookies",
  "AdChoices",
  "Terms",
  "Help",
  "Contact uploading and non-users",
];
